# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from color_gradient_vision/ColorAndPositionPairs.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import color_gradient_vision.msg

class ColorAndPositionPairs(genpy.Message):
  _md5sum = "cc8e80026229df02835845177e306a2f"
  _type = "color_gradient_vision/ColorAndPositionPairs"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """ColorAndPosition[] pairs

================================================================================
MSG: color_gradient_vision/ColorAndPosition
float32 x
float32 y
uint8 R
uint8 G
uint8 B
"""
  __slots__ = ['pairs']
  _slot_types = ['color_gradient_vision/ColorAndPosition[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       pairs

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ColorAndPositionPairs, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.pairs is None:
        self.pairs = []
    else:
      self.pairs = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.pairs)
      buff.write(_struct_I.pack(length))
      for val1 in self.pairs:
        _x = val1
        buff.write(_get_struct_2f3B().pack(_x.x, _x.y, _x.R, _x.G, _x.B))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.pairs is None:
        self.pairs = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.pairs = []
      for i in range(0, length):
        val1 = color_gradient_vision.msg.ColorAndPosition()
        _x = val1
        start = end
        end += 11
        (_x.x, _x.y, _x.R, _x.G, _x.B,) = _get_struct_2f3B().unpack(str[start:end])
        self.pairs.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.pairs)
      buff.write(_struct_I.pack(length))
      for val1 in self.pairs:
        _x = val1
        buff.write(_get_struct_2f3B().pack(_x.x, _x.y, _x.R, _x.G, _x.B))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.pairs is None:
        self.pairs = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.pairs = []
      for i in range(0, length):
        val1 = color_gradient_vision.msg.ColorAndPosition()
        _x = val1
        start = end
        end += 11
        (_x.x, _x.y, _x.R, _x.G, _x.B,) = _get_struct_2f3B().unpack(str[start:end])
        self.pairs.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2f3B = None
def _get_struct_2f3B():
    global _struct_2f3B
    if _struct_2f3B is None:
        _struct_2f3B = struct.Struct("<2f3B")
    return _struct_2f3B
