// Generated by gencpp from file color_gradient_vision/ColorAndPosition.msg
// DO NOT EDIT!


#ifndef COLOR_GRADIENT_VISION_MESSAGE_COLORANDPOSITION_H
#define COLOR_GRADIENT_VISION_MESSAGE_COLORANDPOSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace color_gradient_vision
{
template <class ContainerAllocator>
struct ColorAndPosition_
{
  typedef ColorAndPosition_<ContainerAllocator> Type;

  ColorAndPosition_()
    : x(0.0)
    , y(0.0)
    , R(0)
    , G(0)
    , B(0)  {
    }
  ColorAndPosition_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , R(0)
    , G(0)
    , B(0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef uint8_t _R_type;
  _R_type R;

   typedef uint8_t _G_type;
  _G_type G;

   typedef uint8_t _B_type;
  _B_type B;





  typedef boost::shared_ptr< ::color_gradient_vision::ColorAndPosition_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::color_gradient_vision::ColorAndPosition_<ContainerAllocator> const> ConstPtr;

}; // struct ColorAndPosition_

typedef ::color_gradient_vision::ColorAndPosition_<std::allocator<void> > ColorAndPosition;

typedef boost::shared_ptr< ::color_gradient_vision::ColorAndPosition > ColorAndPositionPtr;
typedef boost::shared_ptr< ::color_gradient_vision::ColorAndPosition const> ColorAndPositionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::color_gradient_vision::ColorAndPosition_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::color_gradient_vision::ColorAndPosition_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace color_gradient_vision

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'color_gradient_vision': ['/home/cc/ee106a/fa19/class/ee106a-acl/project_workspace/src/color_gradient_vision/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::color_gradient_vision::ColorAndPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::color_gradient_vision::ColorAndPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::color_gradient_vision::ColorAndPosition_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::color_gradient_vision::ColorAndPosition_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::color_gradient_vision::ColorAndPosition_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::color_gradient_vision::ColorAndPosition_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::color_gradient_vision::ColorAndPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1e1019b42bbcb03ae038bf01961c3e51";
  }

  static const char* value(const ::color_gradient_vision::ColorAndPosition_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1e1019b42bbcb03aULL;
  static const uint64_t static_value2 = 0xe038bf01961c3e51ULL;
};

template<class ContainerAllocator>
struct DataType< ::color_gradient_vision::ColorAndPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "color_gradient_vision/ColorAndPosition";
  }

  static const char* value(const ::color_gradient_vision::ColorAndPosition_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::color_gradient_vision::ColorAndPosition_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n\
float32 y\n\
uint8 R\n\
uint8 G\n\
uint8 B\n\
";
  }

  static const char* value(const ::color_gradient_vision::ColorAndPosition_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::color_gradient_vision::ColorAndPosition_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.R);
      stream.next(m.G);
      stream.next(m.B);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ColorAndPosition_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::color_gradient_vision::ColorAndPosition_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::color_gradient_vision::ColorAndPosition_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "R: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.R);
    s << indent << "G: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.G);
    s << indent << "B: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.B);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COLOR_GRADIENT_VISION_MESSAGE_COLORANDPOSITION_H
